# Generated by Django 3.2.5 on 2021-07-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20210725_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
    ]
